# Generated by Django 4.2.1 on 2023-05-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='products/')),
                ('name', models.CharField(max_length=70)),
                ('desc', models.TextField(max_length=470, null=True)),
            ],
        ),
    ]
