# Generated by Django 4.2.1 on 2023-05-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
