# Generated by Django 4.2.1 on 2023-05-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='image',
        ),
    ]
