# Generated by Django 4.2.1 on 2023-05-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_photo_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
