# Generated by Django 4.2.1 on 2023-05-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
